DROP DATABASE IF EXISTS animals;

CREATE DATABASE IF NOT EXISTS animals;

USE animals;

-- CREATION DES TABLES ET DES DONNEES.

CREATE TABLE animal
(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
espece VARCHAR(40) NOT NULL,
sexe CHAR(1),
date_naissance DATETIME NOT NULL,
commantaires TEXT,
nom VARCHAR(30),
PRIMARY KEY (id)
)
ENGINE=INNODB;

SHOW TABLES; 

DESCRIBE animal;